# Blog info
blog_name: BlueSun
slogan: å†™å–ä¸€ææ¸…ç˜¦ç«¹ï¼Œç§‹é£æ±Ÿä¸Šä½œæ–‡ç« 
url: http://huang-jerryc.com/

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: huang-jerrryc,JerryC8080,jerryc,JC_Huang,å‰ç«¯,è®¾è®¡,å‰ç«¯å¼€å‘,ç”¨æˆ·ä½“éªŒ,è®¾è®¡,frontend,design,nodejs,JavaScript

home_nav:
  - name: Blog
    url: /archives
  - name: GitHub
    url: https://github.com/JerryC8080
    target: _blank
  - name: Jianshu
    url: http://www.jianshu.com/users/843d2366f95b/latest_articles
    target: _blank
  - name: SF
    url: https://segmentfault.com/u/jerryc
    target: _blank
  - name: About Me
    url: /about

# config page nav
page_nav:
  - name: åšå®¢
    url: /archives/
    target_blank: false # ä¸åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: åˆ†ç±»
    url: /category/
    target_blank: false
  - name: æ ‡ç­¾
    url: /tag/
    target_blank: false
  - name: å‹é“¾
    url: /link/
    target_blank: false
  - name: å…³äº
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # åœ¨æ–°é¡µé¢æ‰“å¼€
  - name: æœç´¢
    url: /search/
    target_blank: false # åœ¨æ–°é¡µé¢æ‰“å¼€

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# é¢åŒ…å±‘
breadcrumb:
  isShow: true # true|fase

# ç›’å­
toolbox:
  isShow: true # true|fase
  text: ç›’å­

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: äº¤æ¢å‹é“¾å¯ä»¥é‚®ä»¶ huangjerryc@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: æ”¯æŒä¸€ä¸‹
  tip: æ‰«ä¸€æ‰«ï¼Œæ”¯æŒJerryC
  items:
    - type: å¾®ä¿¡
      text: å¾®ä¿¡æ‰«ä¸€æ‰«
      imgUrl: /images/qr-wechat.jpg
    # - type: æ”¯ä»˜å®
    #   text: æ”¯ä»˜å®æ‰«ä¸€æ‰«
    #   imgUrl: /images/qr-alipay.png



post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# ä¸ªæ€§åŒ–è®¾ç½®
# =========================================================

# Custom CSS style, æ¨èæŠŠæ ·å¼æ–‡ä»¶æ”¾åœ¨blogæºç æ–‡ä»¶å¤¹ï¼Œè€Œä¸æ˜¯ä¸»é¢˜é‡Œé¢
personal_style: /css/personal-style.css

# è¿™ä¸ªå€¼å–å†³äºä½ å¾—èƒŒæ™¯å›¾ç‰‡æ˜¯æ·±è‰²è¿˜æ˜¯æµ…è‰²ï¼Œæ·±è‰²ç”¨darkï¼Œæµ…è‰²ç”¨light
home_background_scheme: light # darkã€light

# custom font-family æš‚æ—¶åªæ”¯æŒè¿™3ç§è‹±æ–‡å­—ä½“ï¼Œä½ å¯ä»¥å®Œå…¨è‡ªå®šä¹‰å­—ä½“(çœ‹æ–‡æ¡£)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# ç¬¬ä¸‰æ–¹æœåŠ¡
# =========================================================
# Stats
google_analytics: UA-83430919-1
baidu_analytics: b65b3ffc3fd0d14c968e1036793e631b

# Comment service

disqus_shortname: bluesun-jerryc
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#æœ‰è¨€ç”¨æˆ·ç¼–å·
# uyan_key:

# ç•…è¨€, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  è¿™é‡Œå¼€å¯
  changyan_appid:
  changyan_appkey:

# gitalkè¯„è®ºç»„ä»¶ï¼ŒæŠŠä¸‹é¢çš„é…ç½®æ¢æˆä½ çš„ï¼Œå®˜æ–¹æ–‡æ¡£: https://gitalk.github.io/
gitalk:
  enable: false # å¦‚æœä½¿ç”¨ gitalkï¼Œè¯·è®¾ç½®æ”¹ä¹‹ä¸ºtrue
  clientID: 
  clientSecret: 
  repo: BlueSun-Comment
  owner: JerryC8080
  admin: JerryC8080


# gitment comment service
gitment:
  enable: false  # true | false  è¿™é‡Œå¼€å¯
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # å¦‚æœä½¿ç”¨valineï¼Œè¯·è®¾ç½®æ”¹ä¹‹ä¸ºtrue
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size




# ä¸ç®—å­,æ–‡ç« è®¿é—®é‡ç»Ÿè®¡å’Œæ˜¾ç¤º
busuanzi: true

# =========================================================
# é¡µé¢å†…å®¹è®¾ç½®
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
     - "JerryC"
     - "å›å­ï¼Œåšç§¯è–„å‘ä¹Ÿ"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@JerryC8080"
    text_value_url: https://github.com/JerryC8080
  - type: CNode
    text_key: CNode
    text_value: "@JerryC8080"
    text_value_url: https://cnodejs.org/user/JerryC8080
  - type: SegmentFault
    text_key: SegmentFault
    text_value: "@JerryC"
    text_value_url: https://segmentfault.com/u/jerryc
  - type: ç®€ä¹¦
    text_key: ç®€ä¹¦
    text_value: "@JC-Huang"
    text_value_url: http://www.jianshu.com/users/843d2366f95b/latest_articles
  - type: Weibo
    text_key: å¾®åš
    text_value: "@å¤§å¤§å¤§å¤§å¤§å¤§åŸ¹æ°"
    text_value_url: http://weibo.com/2254858394
  - type: mail
    text_key: Gmail
    text_value: "huangjerryc@gmail.com"
  - type: location
    icon: icon-location
    text_value: æ·±åœ³

link:
  - name: Xie Zefan
    info: xxx
    url: http://xiezefan.me/
    avatar: http://xiezefan.qiniudn.com/avatar.jpg

project:
  - type: personal
    name: BeautyWe.js
    url: https://github.com/beautywe/beautywe
    intro: ğŸ‘¨â€ğŸ’»â€ Write beautiful code for wechat mini app by the beautiful we!
  - type: personal
    name: Memeye
    url: https://github.com/JerryC8080/Memeye
    intro: ğŸ‘€ The eye of memory. A lightweight memory monitor and dashboard for Node.js application on development.
  - type: personal
    name: super-cache
    url: https://github.com/JerryC8080/super-cache
    intro: ğŸ’¾ ä¸€ä¸ªè·¨ JS å¹³å°çš„ç¼“å­˜åº“ï¼Œæ”¯æŒç¼“å­˜é€»è¾‘ä»£ç†ï¼Œæ”¯æŒè‡ªå®šä¹‰æ•°æ®å­˜å‚¨